name: Essential Test

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - name: Lint
        run: npx nx lint --outputFile=""

      - name: Lint report
        run: npx nx lint --format ./tools/sonarqube-linter-reporter.js

      - name: Archive lint report results
        uses: actions/upload-artifact@v2
        with:
          name: lint-report-${{ github.sha }}
          path: reports

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - run: npx nx build

      - name: Archive build result
        uses: actions/upload-artifact@v2
        with:
          name: library-dist-${{ github.sha }}
          path: dist

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx nx test --code-coverage

      - if: matrix.node-version == 16
        name: Archive coverage report
        uses: actions/upload-artifact@v2
        with:
          name: ngx-deploy-npm-coverage-report-${{ github.sha }}
          path: coverage/packages/ngx-deploy-npm/lcov.info
