name: Publishment
on:
  push:
    branches:
      - master
jobs:
  test:
    uses: bikecoders/ngx-deploy-npm/.github/workflows/basic-test.yml@master #@master

  analysis:
    name: SonarCloud Main Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_SCANNER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-preliminar:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

      - name: Preliminar Version
        run: npx nx version-preliminar

  release:
    environment: production
    runs-on: ubuntu-latest
    needs: release-preliminar
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

      - name: git config
        shell: bash
        run: |
          git config user.name "Github Actions"
          git config user.email "-"

      - uses: ./.github/actions/download-build

      - name: Check npm credentials
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Use npx instead of yarn because yarn automagically sets NPM_* environment variables
          # like NPM_CONFIG_REGISTRY so npm publish ends up ignoring the .npmrc file
          # which is set up by `setup-node` action.

      - name: Version and Publishment
        run: npx nx version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag last-release
        run: git tag -f last-release

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2.5.0
        with:
          token: ${{ secrets.MANAGE_REPO_TOKEN }}
          branch: master
          tags: true
          unprotect_reviews: true
